/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_skyworth_sernorvalue_method_BtMouseProtocl */

#ifndef _Included_com_skyworth_sernorvalue_method_BtMouseProtocl
#define _Included_com_skyworth_sernorvalue_method_BtMouseProtocl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_skyworth_sernorvalue_method_BtMouseProtocl
 * Method:    TraIntToByte
 * Signature: (III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_skyworth_sernorvalue_method_BtMouseProtocl_TraIntToByte
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_skyworth_sernorvalue_method_BtMouseProtocl
 * Method:    TraByteToInt
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_com_skyworth_sernorvalue_method_BtMouseProtocl_TraByteToInt
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_skyworth_sernorvalue_method_BtMouseProtocl
 * Method:    TraByteToooont
 * Signature: ([B)[I
 */
JNIEXPORT jintArray JNICALL Java_com_skyworth_sernorvalue_method_BtMouseProtocl_TraByteToooont
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
